development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_development
  secret_key_base: rails credentials:edit
  pool: 5
  timeout: 5000
